import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/nav/Navbar";
import Footer from "@/components/footer/Footer";
import AuthProvider from "./AuthProvider";

const inter = Inter({ subsets: ["latin"] });

const kaleko = localFont({ src: "../public/fonts/Kaleko105Light.ttf" });

export const metadata = {
  title: "Avion Realty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-black text-white">
      <body className={kaleko.className}>
        <AuthProvider> <div className="">
          {/* navbar */}
          <Navbar />

          {/* dynamic content */}
          <div className="min-h-screen">{children}</div>

          {/* footer */}
          <Footer />
        </div> </AuthProvider>
      </body>
    </html>
  );
}
