import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Avion Realty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-black text-white">
      <body className={inter.className}>
        {/* navbar */}
        <Navbar />

        {/* dynamic content */}
        <div className="min-h-screen">{children}</div>

        {/* footer */}
        <Footer />
      </body>
    </html>
  );
}
